### ISSUE TITLE
Verify Code for Two Ball Shooter Motors

### ISSUE THREAD

**Issue by AmandaKline** [The-Charge/SirLancebot2016#11]
This should be in the code already, check it.

**Comment by maansi-dasari** [comment]
Still need to change the shoot() method under the Shooter subsystem to account for the PID values.

**Comment by AmandaKline** [comment]
@maansi-dasari I don't think you pushed your code

Edit: you did, just to Staging not a new branch.

**Comment by AmandaKline** [comment]
Finished what @maansi-dasari started. PIDs should be integrated now.

**Comment by maansi-dasari** [comment]
Done. Once the shooters are on the robot we need to check to make sure they're spinning in the right direction.
