### ISSUE TITLE
Test Button Box

### ISSUE THREAD

**Issue by AmandaKline** [The-Charge/SirLancebot2016#12]
Treat it like a joystick. Any things that turn will act like joystick axis, any things you can push act like joystick buttons.
- [x] Set up Horse in RB to have the correct buttons and commands that go with them
- [x] Test

**Comment by AmandaKline** [comment]
Commands that we need:
**Using potentiometers on the button box**
- [x] 1. Shooter speed control
- [x] 2. Raise and lowering arm speed
- [ ] 3. ??? Use one to set an angle we want to turn for shooting adjustment. It would simulate a camara input. 

**Using the switches**
- [x] 1. Switch for each roller on
        a. while-pressed button for forward, and another for backward
- [x] 2. Shoot command - "while pressed"
        a. Would start shoot process: get wheels to speed, get plunger ready...

**Buttons**
- [x] 1. A fire button for final shoot command
- [x] 2. Bop
- [x] Edit Button Numbers to correspond to the Button Box

**Comment by AmandaKline** [comment]
The potentiometers are set up as the different axis of a regular joystick. 

Top Left: x axis
Top Middle: y-axis
Top Right: z axis
Bottom Left: x rotate
Bottom Middle: y rotate
Bottom Right: slider

To get at the values of the potentiometers, use horse.getX(), etc.

**Comment by abcurrie** [comment]
Bottom Right: slider

**Comment by AmandaKline** [comment]
Shooter speed is controlled by top left pot
Arm speed is controlled by top middle pot

**Comment by AmandaKline** [comment]
Current Button Layout:

<pre>
--------------------------------------------------------------------------
|  {Outer Intake Reverse}    {Outer Intake Forward}
|  {Inner Intake Reverse}     {Inner Intake Forward}
|  {       -----          }     {       -------         }
|  {   Prepare to Shoot   }     {            Shoot            }
------------------------------------------------------------------------------
</pre>

**Comment by AmandaKline** [comment]
Add Buttons for ShiftHigh and ShiftLow
