### ISSUE TITLE
Develop Code to Prevent Blowing Arms Gearbox

### ISSUE THREAD

**Issue by AmandaKline** [The-Charge/SirLancebot2016#14]
Facts (from Mr. Z) about a 1000:1 gearbox:
- Theoretical Torque capabilities: 4000 in-lbs aka 330 ft-lbs
  - Recommendations from Vex: only use a small fraction of this power
- Torque needed: 10 lbs at 16 in: 160 in-lbs
  - Possible to run both arms from a single motor and gear box

Task: Develop a way to interrupt a go-to position command if the torque on the gearbox suddenly skyrockets. 

Suggestions:
- "Current Control option on the controller" ( @abcurrie more details on what this is? )

**Comment by Shalmezad** [comment]
For seeing what the current current is: http://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/CANTalon.html#getOutputCurrent--
Documentation on the current control option: http://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/CANTalon.html#set-double-

**Comment by AmandaKline** [comment]
There is a "current" mode (like the "position" and "setVBus" modes) that can set a current set point and the motor will try to get there. This conflicts with our desire to use the position mode. 

We would have to make our own very complex function to restrict Amps. 

( from @abcurrie )

**Comment by Shalmezad** [comment]
@abcurrie Had an idea we may want to toy with.
What if we set up a software (roborio) based PID, had our PIDSource be the absolute encoder, and the PIDOutput map to the CANTalon in current mode, but with a cap on the current.

**Comment by mike-r** [comment]
Normally you don't want to "control" based on current. You want to limit the maximum current. 

Run the motor until the position set point is reached, or the current hits some limit THEN possibly hold that current value until the set point or a timeout is reached. 

Mike
