### ISSUE TITLE
Account for distance when shooting

### ISSUE THREAD

**Issue by AmandaKline** [The-Charge/SirLancebot2016#15]
- [ ] Test speed necessary at every foot
       - Every half foot if it's a big difference
- [ ] ~~Store these values as constants in the code~~
- [ ] Every time the shoot command is called, read the vision code to check our distance and set the speed accordingly

**Comment by AmandaKline** [comment]
- [x] The vertical height of the vision tape around the targets has changed from 14 in to 12 in, this needs to change in the vision code
- [ ] Using the data colected above, create a polinomial curve. X values are distance, y values are shoot speed

**Comment by CrystalENVT** [comment]
Actually, the vision tape was changed from 14 to 12 inches, and that has already been completed within the vision code. (this is instead of the 16 in to 14 in that was previously mentioned)

**Comment by CrystalENVT** [comment]
Since the vision code is essentially done (except for minor tweaks) I can help work on this

**Comment by AmandaKline** [comment]
@Travis-Team2619 , just making sure that you know we can't do much, if anything at all, on this issue until we have the final shooter, or a similar shooter that we could hook up to plybot, from mechanical.

**Comment by CrystalENVT** [comment]
We need to use the Speed setting from the Pot and the distance returned by the vision code. This will be a huge difference. Also, these will no be used as constants, but instead put into Excel and a polynomial equation created.
