### ISSUE TITLE
The robotbuilder file does not jive with the java files.  if you go into robot builder and export to java the files will not compile

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/SirLancebot2016#17]

**Comment by AmandaKline** [comment]
This may be a result of @maansi-dasari and my merge issues from last night: we tried to keep everything in the .yaml file but it may have been messed up. I'll look into that now.

**Comment by AmandaKline** [comment]
It compiles for me now. There were some issues involving the BallScooper thinking it belonged to the Camara subsystem. They should be all cleared up.
