### ISSUE TITLE
Autonomous Commands

### ISSUE THREAD

**Issue by AmandaKline** [The-Charge/SirLancebot2016#21]
Code for from every starting position through defense spots 2 - 5 (not 1 that's the low bar)

**Comment by AmandaKline** [comment]
Determine field markings that will allow Drive Team to position the robot in exactly the right spot for each starting spot we want to have

**Comment by Shalmezad** [comment]
Here's a hint:

```
//Robot.java
public void autonomousInit(){
     Command defenseCommand = defenseSendableChooser.getSelected();
     Command turnCommand = positionSendableChooser.getSelected();
     Command autonomousCommand = new SelectedAutonomousCommand(defenseCommand, turnCommand);
     autonomousCommand.start();
}
```

Like I said before, once a CommandGroup is constructed, there's no changing it. I never said you couldn't change how/where it's constructed.

**Comment by AmandaKline** [comment]
In the SC code, we currently have a positionSendableChooser called autoposition. 
- [x] Make defenseSendableChooser
- [x] Add positionSendableChooser option for spy box

**Comment by TheRichWalrus506** [comment]
From the top to the bottom alignment lines on the right, the angles are
1. 50.19
2. 34.99
3. 19.29
4. -5.71
5. -28.81

**Comment by TheRichWalrus506** [comment]
- [x] Account for the fact that we will start with our arms up, and will need to keep them down for some autonomous commands
- [x] When shooting, make sure our shooter is actually up and our arms are not in the way
