### ISSUE TITLE
Delinearize Shoot Speed Pot

### ISSUE THREAD

**Issue by TheRichWalrus506** [The-Charge/SirLancebot2016#26]
In the MathUtil Library, create a new method
- [ ] take in a speed
- [ ] multiply it by 2
- [ ] decide on a minimum speed one would like to shoot at, such as .4
- [ ] format the deliniearization so that the shooter pot turned all the way down gives that minimum speed, and that when it is turned all the way up it gives one. 

**Remeber**: The raw pot values will range from -1 to 1

**Comment by AmandaKline** [comment]
How it actually works:
- Take in -1 to 1 speed
- multiplies by .3
- adds .7
  The new outputs will be from .4 to 1
