### ISSUE TITLE
Fix Vision Tracking Power Problems

### ISSUE THREAD

**Issue by AmandaKline** [The-Charge/SirLancebot2016#29]
Nook looses power = no vision tracking. :cry:

**Comment by AmandaKline** [comment]
Flux Capacitor (aka a power adapter) made and ready for installation! Tested with @Travis-Team2619 's laptop straped to plybot - seems ready to go.

**Comment by CrystalENVT** [comment]
Satyajit has the Flux Capacitor in the "Do Not Touch" area with the self tapping screws. Install involves removing the old power adapter, screwing in the FC above the pneumatic wheel on the right side of the robot, and zip-tying wires (for wire management)
