### ISSUE TITLE
Rework Shooter Code

### ISSUE THREAD

**Issue by AmandaKline** [The-Charge/SirLancebot2016#35]
The button(s) for the button box that interact with the shooter are going to be "When Pressed" buttons. The current code configuration does not function as such, and we are going to rework the shooter code in a similar manner to the solenoids.

----------------------------------------------- Part 1 -----------------------------------------
- [x] 1. Create two booleans, one to indicate if the shooter motors are running and the other to indicate if they are running forward or in reverse. Good names include shooterMotorsOn (so the code will read "if(shooterMotorsOn)" or "if(!shooterMotorsOn)") and shooterMotorsForward, etc.
  - Check where you define these booleans for future reference:
  - [ ] Constants Class
  - [x] Shooter Subsystem
- [x] 2. Create a new command that will run all commands for the shooter subsystem. Good names include ShooterRun, ShooterControl, etc. 
  - The execute() of this command needs to:
  - [x] Read motors-running boolean, if it says the motors are not running set the motor speed to 0 _You may want to call the stop() method in the ShooterMotors subsystem_
  - [x] If the motors are running according to the boolean, call shooterMotors.calcSpeed() (see below)
- [x] 3. In the ShooterMotors subsystem, create a method called calcSpeed. 
- It will replace all of the speed-setting methods other than stop(), but don't delete them until you are ready to move on to step 4
  - [x] If the motor direction boolean says we are running in reverse, set the shooter motors to a fixed speed (check what speed we use in the spit() method currently)
  - [x] If the direction boolean says we are running forward, for now read the pot and set the speed 
        accordingly. _Other considerations will be added here in Part 2_ When you get to this point, check or ask for help checking if the shooter speed pot is still being delinearized.
- [x] 4. Rework all shooter commands to only set an appropriate boolean and immediately terminate. 

----------------------------------------------- Part 2 -----------------------------------------
In calcSpeed, if we are shooting forward:
- [x] If we are shooting at the low goal, set the motors at a fixed speed
- [x] If we are shooting at the high goal, check if vision is working. If it is, call the method we are using to shoot according to camara distance. It's in the CamaraSubsystem.
  - [x] If the vision is not working, read the speed from the pot as coded earlier

**Comment by CrystalENVT** [comment]
As a portion of Part 2, we need to get the Auto-Distance-Speed setup

**Comment by AmandaKline** [comment]
The shooter subsystem now works! Distance still needs to be calculated, a new issue is being created.
