### ISSUE TITLE
Ball Sensor 

### ISSUE THREAD

**Issue by AmandaKline** [The-Charge/SirLancebot2016#36]
Program a "digital IO" for the ball sensor
     - right now you get a 5 volt signal when there is a ball and 0 volts when there is not a ball
Ask @abcurrie for help and more clarification

**Comment by Shalmezad** [comment]
Assuming it's a standard digital IO:
Use RobotBuilder,
There's a digital input in your sensor list
Add it to a subsystem that makes sense, or it's own
The method you want is yourDigitalInputName.get() which will return a boolean. True for 5v, false for 0v
See: http://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/DigitalInput.html#get--

**Comment by ammenzl7** [comment]
Done.
