### ISSUE TITLE
Fix DriveXFeet

### ISSUE THREAD

**Issue by AmandaKline** [The-Charge/SirLancebot2016#4]
- [x] Clear integral in init position mode
- [x] Test
- [x] Merge to staging

**Comment by Shalmezad** [comment]
Note, the method you want is:
CANTalon#ClearIaccum()

**Comment by AmandaKline** [comment]
That method was implemented yesterday, I believe on a branch called PIDWork

**Comment by AmandaKline** [comment]
Mr. Currie's thoughts for speed control:
- The Position PID is pretty normal
  - There is actually a P, I, D, and F. 
- Look at "I Zone" variable: if the integral gets above some value it clears it's self out
  - Right now our integral is huge and is causing us to be going as fast as we let ourselves even when we get really close to our target
  - [x] Set up and test I Zone as 4000. Do it in the same place where we set our P, I, and D values
  - use motor.SetIzone(izone);
- The way the CANTalon is set up the integral doesn't come into play until the end of the process (apparently this is a weird way of doing this)
